services:
  app:
    container_name: admin-next-bus
    image: trdp/next-bus-admin:latest
    ports:
      - '3000:80'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    env_file:
      - .env
