services:
  app:
    container_name: admin-next-bus
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '3000:80'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    env_file:
      - .env
