version: '3.8'

services:
  app:
    container_name: admin-next-bus
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: ${BUILD_ENV}
        ESLINT_USE_FLAT_CONFIG: ${ESLINT_USE_FLAT_CONFIG}
        FIREBASE_API_DOMAIN: ${FIREBASE_API_DOMAIN}
        FIREBASE_API_KEY: ${FIREBASE_API_KEY}
        FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
        FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
        FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
        FIREBASE_APP_ID: ${FIREBASE_APP_ID}
        FIREBASE_MEASUREMENT_ID: ${FIREBASE_MEASUREMENT_ID}
        GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
        REST_API_ROOT: ${REST_API_ROOT}
        REST_API_VERSION: ${REST_API_VERSION}
        GOOGLE_PLACE_API_ROOT: ${GOOGLE_PLACE_API_ROOT}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
