version: '3.8'

services:
  app:
    container_name: admin-next-bus
    image: admin-next-bus
    build:
      context: .
      # env_file:
      #   - .env
      args:
        - BUILD_ENV=local
        - ESLINT_USE_FLAT_CONFIG=true
        - FIREBASE_API_DOMAIN=FIREBASE_API_DOMAIN
        - FIREBASE_API_KEY=FIREBASE_API_KEY
        - FIREBASE_PROJECT_ID=FIREBASE_PROJECT_ID
        - FIREBASE_STORAGE_BUCKET=FIREBASE_STORAGE_BUCKET
        - FIREBASE_MESSAGING_SENDER_ID=FIREBASE_MESSAGING_SENDER_ID
        - FIREBASE_APP_ID=FIREBASE_APP_ID
        - FIREBASE_MEASUREMENT_ID=FIREBASE_MEASUREMENT_ID
        - FONTAWESOME_NPM_AUTH_TOKEN=FONTAWESOME_NPM_AUTH_TOKEN
    ports:
      - 3000:3000
